"""Add skin_tone to users

Revision ID: 83e1618332cb
Revises: 4556d97cc931
Create Date: 2025-05-14 21:22:27.300436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83e1618332cb'
down_revision: Union[str, None] = '4556d97cc931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'skin_tone')
    op.add_column('users', sa.Column('skin_tone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skin_tone')
    op.add_column('user_preferences', sa.Column('skin_tone', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
