"""Add Shoes to Preferences

Revision ID: f10539bb0408
Revises: a2b3c4d5e6f7
Create Date: 2025-05-14 22:27:57.631214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10539bb0408'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('footwear', sa.Enum('ANY', 'CASUAL_SHOES', 'FORMAL_SHOES', 'SPORTS_SHOES', 'SANDALS', 'HEELS', 'FLATS', 'FLIP_FLOPS', 'SAREE', name='footwear'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'footwear')
    # ### end Alembic commands ###
